export const ProductsExample = [
  {
    name: "Eren",
    stock: 4,
    type: "Accesorio",
    price: 300,
    description: "Poster de la batalla de Eren contra el Titan Acorazado.",
    img: "https://www.placecage.com/640/360",
    key: "#001",
  },
  {
    name: "Deku",
    stock: 2,
    type: "Ropa",
    price: 1500,
    description: "Remerita",
    img: "https://www.placecage.com/640/360",
    key: "#002",
  },
  {
    name: "Lord Stark",
    stock: 100,
    type: "Accesorio",
    price: 20,
    description: "Espada para los caminantes blancos",
    img: "https://www.placecage.com/640/360",
    key: "#003",
  },
  {
    name: "Vacio Purpura",
    stock: 1,
    type: "Accesorio",
    price: 180,
    description: "Vacio purpura de Gojo encerrado en una capsula.",
    img: "https://www.placecage.com/640/360",
    key: "#004",
  },
  {
    name: "Orgrimar",
    stock: 84,
    type: "Pantalones",
    price: 999,
    description: "Para defender la capital de la Horda de la Alianza.",
    img: "https://www.placecage.com/640/360",
    key: "#005",
  },
];
